### PR TITLE
Adding .env.sample and fixing small typo

### PR DESCRIPTION
**Pull request by heitortsergent**
- Adding a .env.sample file with all the environment variables to make it easier to set it up
- Adding `Dotenv.load` to app.rb, helps run the app without foreman
- Updating README.md with instructions to use the `.env.sample` file and fixing a small typo on the Slack Setup section

### CODE REVIEW

**Comment by josephwegner** [comment]
Hey @heitortsergent! This is awesome!

One quick thing - could you add `SLACK_WEBHOOK_URL=YOUR_WEBHOOK_URL` to the `.env.sample`? I think the flow might get confusing if the user is expecting all of the necessary env variables to already be in `.env.sample`.

Thanks a bunch!

**Comment by heitortsergent** [comment]
@josephwegner done, and thanks! I had added it to my `.env`, forgot to add it to `.env.sample` :dancer:

**Comment by josephwegner** [comment]
+1 from me, after Travis.

@hex337 look good?

**Comment by hex337** [comment]
:+1:

**Pull request merged**
